[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "frobs_rl"
authors = [{name = "Fajardo", email = "fajardo@mail"}]
dynamic = ["version", "description"]
